substitutions:
  _SERVICE: "billing-api"
  _REGION: "europe-west1"
  _REPO: "billing-repo"
  _IMAGE: "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/billing-api"

steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build","-t","${_IMAGE}:${SHORT_SHA}","-t","${_IMAGE}:latest","."]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - "${_SERVICE}"
      - "--image=${_IMAGE}:latest"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--quiet"
      # - "--allow-unauthenticated"  # déjalo comentado si usas IAM

images:
  - "${_IMAGE}:${SHORT_SHA}"
  - "${_IMAGE}:latest"
