# cloudbuild.yaml (CORRECTO)
substitutions:
  _SERVICE: "billing-api"
  _REGION: "europe-west1"
  _REPO: "billing-repo"
  _IMAGE: "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/billing-api"

steps:
  # 1) Build de la imagen y tag a Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "-t"
      - "${_IMAGE}:${SHORT_SHA}"
      - "-t"
      - "${_IMAGE}:latest"
      - "."

  # 2) Deploy a Cloud Run usando la imagen recién construida
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - "${_SERVICE}"
      - "--image=${_IMAGE}:${SHORT_SHA}"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--quiet"
      # Quita el comentario de la siguiente línea SOLO si quieres público sin IAM:
      # - "--allow-unauthenticated"

images:
  - "${_IMAGE}:${SHORT_SHA}"
  - "${_IMAGE}:latest"
